import { Router } from "express";
import { authorize } from "../middleware/auth.js";
import { createRole, createUser, dashboard, deletePermission, deleteRole, deleteUser, listAuditLogs, listPermissions, listRoles, listUsers, savePermission, updateRole, updateUser } from "../controllers/adminController.js";
import { adminDonations } from "../controllers/donationController.js";
import { listMessages, updateMessageStatus } from "../controllers/contactController.js";
import { updateSettings } from "../controllers/settingsController.js";
import { upload } from "../middleware/upload.js";
import { uploadFile } from "../controllers/uploadController.js";

const router = Router();
router.get("/dashboard", dashboard);
router.get("/users", authorize("users.view"), listUsers);
router.post("/users", authorize("users.create"), createUser);
router.put("/users/:id", authorize("users.edit"), updateUser);
router.delete("/users/:id", authorize("users.delete"), deleteUser);
router.get("/roles", authorize("roles.view"), listRoles);
router.post("/roles", authorize("roles.create"), createRole);
router.put("/roles/:id", authorize("roles.edit"), updateRole);
router.delete("/roles/:id", authorize("roles.delete"), deleteRole);
router.get("/permissions", authorize("permissions.view"), listPermissions);
router.post("/permissions", authorize("permissions.create"), savePermission);
router.put("/permissions/:id", authorize("permissions.edit"), savePermission);
router.delete("/permissions/:id", authorize("permissions.delete"), deletePermission);
router.get("/audit-logs", authorize("users.view"), listAuditLogs);
router.get("/contact-messages", authorize("contact_messages.view"), listMessages);
router.patch("/contact-messages/:id", authorize("contact_messages.read"), updateMessageStatus);
router.put("/settings", authorize("settings.edit"), updateSettings);
router.get("/donations", authorize("donations.view"), adminDonations);
router.get("/transactions", authorize("transactions.view"), adminDonations);
router.post("/uploads/:scope", upload.single("file"), uploadFile);
export default router;
