import ContactDetails from "./ContactDetails";
import { PublishedContentSection } from "./PublishedContent";
import { ArrowRight, BarChart3, BookOpen, BriefcaseBusiness, Building2, CheckCircle2, HeartPulse, Lightbulb, Users } from "lucide-react";

const approach = ["Understand", "Assess", "Design", "Partner", "Implement", "Monitor", "Evaluate", "Scale"];
function SectionHeading({ label, title, children }) { return <div className="section-heading"><span>{label}</span><h2>{title}</h2>{children && <p>{children}</p>}</div>; }
function ContentSections() { return <>
  <section id="about" className="about-section"><div className="container"><SectionHeading label="WHO WE ARE" title="Building Pathways to Inclusive and Sustainable Development">Social Initiative for India Foundation is a Section 8 not-for-profit organisation committed to advancing inclusive, sustainable and community-led development.</SectionHeading><div className="about-grid"><article className="about-card"><HeartPulse className="about-card-icon" /><h3>Our vision</h3><p>An inclusive and sustainable India where every individual and community can live with health, dignity, knowledge, livelihood security and equal access to opportunities.</p></article><article className="about-card"><Lightbulb className="about-card-icon" /><h3>Our mission</h3><p>To improve quality of life through inclusive, participatory and evidence-based access to healthcare, education, livelihoods, skills, technology and essential services.</p></article><article className="about-card"><Users className="about-card-icon" /><h3>Our values</h3><p>Dignity, inclusion, integrity, participation, sustainability, evidence, collaboration, accountability and innovation guide our work.</p></article></div></div></section>
  <PublishedContentSection module="programmes" title="Our Programmes" id="work" />
  <PublishedContentSection module="impact_stories" title="Impact Stories" />
  <PublishedContentSection module="gallery" title="Gallery" />
  <PublishedContentSection module="blogs" title="Latest Blogs" />
  <section id="approach" className="approach-section"><div className="container"><SectionHeading label="OUR APPROACH" title="From Community Needs to Sustainable Solutions">We listen, use evidence and work with communities and institutions to deliver practical programmes with measurable outcomes.</SectionHeading><div className="approach-steps">{approach.map((step, i) => <div key={step}><b>{String(i + 1).padStart(2, "0")}</b><span>{step}</span></div>)}</div><p className="framework"><strong>HEALTH</strong> · <strong>LEARN</strong> · <strong>SKILL</strong> · <strong>EARN</strong> · <strong>EMPOWER</strong> · <strong>SUSTAIN</strong> · <strong>RESEARCH</strong> · <strong>PARTNER</strong></p></div></section>
  <section id="partnerships" className="partnership-section"><div className="container partnership-grid"><div><span className="small-label">CSR & CORPORATE PARTNERSHIPS</span><h2>Turning CSR Commitments into Measurable Community Impact</h2><p>We work with corporates and institutions to design and implement responsible social-development programmes aligned with community needs and organisational priorities.</p><a className="btn btn-primary" href="#contact">Partner with SIFI Foundation <ArrowRight size={17}/></a></div><div className="partnership-visual"><img src="/images/education.jpg" alt="Students learning together in a community classroom" /><div className="partnership-list"><div><Building2/><span>Community needs assessment & programme design</span></div><div><BriefcaseBusiness/><span>Implementation across priority development areas</span></div><div><BarChart3/><span>Monitoring, evaluation, documentation & reporting</span></div><div><BookOpen/><span>Research, baseline studies & social impact assessment</span></div></div></div></div></section>
  <section id="research" className="research-section"><div className="container"><SectionHeading label="RESEARCH & KNOWLEDGE" title="Evidence. Insight. Action.">Reliable evidence helps institutions understand communities, identify priorities, design interventions and measure change.</SectionHeading><div className="research-grid"><div><h3>Baseline studies</h3><p>Establishing the socio-economic and development profile before programme implementation.</p></div><div><h3>Needs assessment</h3><p>Identifying priority gaps through field-based assessment and community consultation.</p></div><div><h3>Monitoring & evaluation</h3><p>Tracking progress, outcomes, quality and programme effectiveness.</p></div><div><h3>Knowledge management</h3><p>Turning field experience into reports, case studies and useful learning documents.</p></div></div></div></section>
  <section id="impact" className="impact-section"><div className="container"><SectionHeading label="IMPACT" title="Measuring What Matters">We look beyond activity counts to understand access, outcomes, inclusion, sustainability and learning.</SectionHeading><div className="impact-list">{["Reach — people and communities reached", "Access — services, information and opportunities", "Outcome — change created through an intervention", "Inclusion — participation of underserved groups", "Sustainability — benefits that can continue", "Learning — insight that improves future work"].map(item => <span key={item}><CheckCircle2 size={18}/>{item}</span>)}</div></div></section>
  <section id="leadership" className="leadership-section"><div className="container"><SectionHeading label="LEADERSHIP & GOVERNANCE" title="Guided by Purpose and Accountability"/><div className="leadership-grid"><article><h3>Mithilesh Pratap Singh</h3><p>Managing Director / Director</p></article><article><h3>Madhu Priya Soni</h3><p>Director</p></article><article><h3>Kunal Singh Rana</h3><p>Director</p></article></div></div></section>
  <section id="get-involved" className="get-involved-section"><div className="container get-involved-content"><div><span className="small-label">GET INVOLVED</span><h2>Be Part of the Change</h2><p>Partner, volunteer, collaborate or contribute expertise to support inclusive and sustainable development.</p></div><a className="btn btn-light" href="#contact">Start a conversation <ArrowRight size={17}/></a></div></section>
  <section id="transparency" className="transparency-section"><div className="container"><SectionHeading label="TRANSPARENCY & ACCOUNTABILITY" title="Responsible. Transparent. Accountable.">We are committed to responsible resource use, applicable compliance, transparent programme management, monitoring, documentation and reporting.</SectionHeading><div className="transparency-links"><span>Governance information</span><span>Programme reports</span><span>Research publications</span><span>Policies & statutory documents</span></div></div></section>
  <section id="policies" className="policies-section"><div className="container"><SectionHeading label="LEGAL & POLICIES" title="Our Commitments and Website Policies">These policies set out how SIFI Foundation handles information, website use, donations, safeguarding and volunteer engagement.</SectionHeading><div className="policy-grid"><details><summary>Privacy Policy</summary><p>We collect only information needed to respond to enquiries, manage programmes, volunteer applications, partnerships and donations, maintain records, improve the website and meet legal obligations. We do not sell personal information. You may contact <a href="mailto:info@sififoundation.org">info@sififoundation.org</a> regarding your information.</p></details><details><summary>Terms of Use</summary><p>Website material is for legitimate personal, educational, research and institutional use. Content must not be misrepresented, used unlawfully, altered misleadingly or reproduced commercially without authorisation. Information may be updated as programmes and activities develop.</p></details><details><summary>Donation, Refund & Cancellation</summary><p>Voluntary contributions support eligible charitable and community-development activities. Refund requests for an error, duplicate or unauthorised transaction may be reviewed on verification. Please contact <a href="mailto:projects@sififoundation.org">projects@sififoundation.org</a> with the transaction details.</p></details><details><summary>Cookie Policy & Disclaimer</summary><p>Cookies and similar technologies may support functionality, security, preferences and website improvement. Programme information, stories and photographs may reflect a particular period and can change. General website information is not professional advice.</p></details><details><summary>Child Safeguarding & Protection</summary><p>We are committed to children’s safety, dignity, privacy and wellbeing. Programme activity seeks to uphold non-discrimination, confidentiality, responsible communication and appropriate reporting. Concerns should be reported through official channels.</p></details><details><summary>Volunteer Terms & Code of Conduct</summary><p>Volunteers must respect communities, protect confidential information and beneficiary privacy, follow programme and safety requirements, and avoid unauthorised publication or representation of the Foundation.</p></details></div></div></section>
  <section id="contact" className="contact-section"><div className="container contact-grid"><div><span className="small-label">CONTACT US</span><h2>Let's Work Together</h2><p>We welcome conversations with corporates, government institutions, development agencies, NGOs, researchers, professionals, volunteers and community representatives.</p></div><ContactDetails /></div></section>
</>; }
export default ContentSections;
