import { useMemo, useState } from "react";
import { ChevronDown, ChevronUp, CopyPlus, Eye, Plus, Save, Trash2 } from "lucide-react";
import { api } from "../lib/api";
import ImageUpload from "./ImageUpload";
import WebsitePreview from "./WebsitePreview";
import { bannerPages, emptySlider, newSlide } from "../../shared/pageSliders";

const normalize = (slider) => ({ enabled: slider?.enabled ?? true, slides: (slider?.slides || []).map((slide) => ({ ...newSlide(), ...slide })) });
export default function PageSliderEditor({ data, canEdit }) {
  const [page, setPage] = useState("/");
  const [sliders, setSliders] = useState(() => Object.fromEntries(bannerPages.map((item) => [item.path, normalize(data[item.path])])));
  const [activeSlide, setActiveSlide] = useState(0);
  const [uploads, setUploads] = useState(0);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const slider = sliders[page] || emptySlider();
  const setSlider = (next) => setSliders((current) => ({ ...current, [page]: next }));
  const addSlide = () => { if (slider.slides.length >= 12) return setMessage("You can add up to 12 slides per page."); const next = [...slider.slides, newSlide()]; setSlider({ ...slider, slides: next }); setActiveSlide(next.length - 1); setMessage(""); };
  const removeSlide = (index) => { const next = slider.slides.filter((_, position) => position !== index); setSlider({ ...slider, slides: next }); setActiveSlide(Math.max(0, Math.min(activeSlide, next.length - 1))); };
  const updateSlide = (index, key, value) => setSlider({ ...slider, slides: slider.slides.map((slide, position) => position === index ? { ...slide, [key]: value } : slide) });
  const move = (index, direction) => { const next = [...slider.slides]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setSlider({ ...slider, slides: next }); setActiveSlide(target); };
  const save = async () => { if (!canEdit || saving || uploads) return; setSaving(true); setMessage(""); try { const saved = await api("/admin/page-sliders", { method: "PUT", body: { page, ...slider } }); setSlider(saved); window.dispatchEvent(new Event("page-sliders-updated")); setMessage("Banner slider saved. It is now live on the selected page."); } catch (error) { setMessage(error.message); } finally { setSaving(false); } };
  const previewPayload = useMemo(() => ({ kind: "banner", path: page, slider, activeSlide }), [page, slider, activeSlide]);
  return <section className="slider-editor"><header className="slider-editor-head"><div><span>PAGE BANNERS</span><h1>Banner sliders</h1><p>Select a page, add one or more slides, and check the actual website preview before saving.</p></div><label><span>Website page</span><select value={page} onChange={(event) => { setPage(event.target.value); setActiveSlide(0); setMessage(""); }}>{bannerPages.map((item) => <option key={item.path} value={item.path}>{item.label}</option>)}</select></label></header>
    <div className="slider-editor-layout"><div className="slider-workspace"><div className="slider-toolbar"><label className="toggle-field"><input type="checkbox" checked={slider.enabled} disabled={!canEdit} onChange={(event) => setSlider({ ...slider, enabled: event.target.checked })} /><span>Show this slider on {bannerPages.find((item) => item.path === page)?.label}</span></label><button type="button" className="btn btn-primary" disabled={!canEdit || slider.slides.length >= 12} onClick={addSlide}><Plus size={17} /> Add slide</button></div>
      {!slider.slides.length && <div className="empty-slider"><Eye size={25} /><h2>No slides yet</h2><p>Click “Add slide” to create the first banner.</p></div>}
      <div className="slide-rows">{slider.slides.map((slide, index) => <article className={index === activeSlide ? "slide-row active" : "slide-row"} key={slide.id}><button type="button" className="slide-row-select" onClick={() => setActiveSlide(index)}><b>{index + 1}</b><span>{slide.title || "Untitled slide"}<small>{slide.image ? "Image added" : "Add a banner image"}</small></span></button><div className="slide-row-actions"><button type="button" aria-label="Move slide up" disabled={!canEdit || index === 0} onClick={() => move(index, -1)}><ChevronUp size={17} /></button><button type="button" aria-label="Move slide down" disabled={!canEdit || index === slider.slides.length - 1} onClick={() => move(index, 1)}><ChevronDown size={17} /></button><button type="button" aria-label="Duplicate slide" disabled={!canEdit || slider.slides.length >= 12} onClick={() => { const next = [...slider.slides]; next.splice(index + 1, 0, { ...slide, id: newSlide().id }); setSlider({ ...slider, slides: next }); setActiveSlide(index + 1); }}><CopyPlus size={17} /></button><button type="button" aria-label="Remove slide" disabled={!canEdit} onClick={() => removeSlide(index)}><Trash2 size={17} /></button></div>
        {index === activeSlide && <div className="slide-fields"><ImageUpload scope="banners" label="Banner image" value={slide.image} disabled={!canEdit || saving} onUploadingChange={(change) => setUploads((count) => count + change)} onChange={(value) => updateSlide(index, "image", value)} /><div className="editor-fields"><label><span>Image description</span><input value={slide.alt} disabled={!canEdit} onChange={(event) => updateSlide(index, "alt", event.target.value)} placeholder="Describe the image for screen readers" /></label><label><span>Small heading</span><input value={slide.eyebrow} disabled={!canEdit} onChange={(event) => updateSlide(index, "eyebrow", event.target.value)} placeholder="For example: COMMUNITY ACTION" /></label><label className="wide"><span>Main heading</span><input value={slide.title} disabled={!canEdit} onChange={(event) => updateSlide(index, "title", event.target.value)} placeholder="Banner heading" /></label><label className="wide"><span>Description</span><textarea rows="3" value={slide.description} disabled={!canEdit} onChange={(event) => updateSlide(index, "description", event.target.value)} placeholder="Short banner text" /></label><label><span>Button text</span><input value={slide.buttonText} disabled={!canEdit} onChange={(event) => updateSlide(index, "buttonText", event.target.value)} placeholder="Learn more" /></label><label><span>Button link</span><input value={slide.buttonUrl} disabled={!canEdit} onChange={(event) => updateSlide(index, "buttonUrl", event.target.value)} placeholder="/donate or https://..." /></label><label><span>Text position</span><select value={slide.align} disabled={!canEdit} onChange={(event) => updateSlide(index, "align", event.target.value)}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label></div></div>}
      </article>)}</div>{message && <p className="form-message" role="status">{message}</p>}<button type="button" className="btn btn-primary slider-save" disabled={!canEdit || saving || uploads > 0} onClick={save}>{saving ? "Saving..." : uploads ? "Uploading..." : <><Save size={17} /> Save banner slider</>}</button></div><WebsitePreview payload={previewPayload} title="Selected page preview" /></div>
  </section>;
}
