// Rebuild the portable content dataset from the supplied UTF-8 foundation profile.
const fs = require('node:fs');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, 'sifi-foundation-source.txt'), 'utf8');
const sections = {};
const matches = [...source.matchAll(/^(\d+)\. ([^\r\n]+)\r?\n/gm)];
for (let i = 0; i < matches.length; i++) sections[Number(matches[i][1])] = source.slice(matches[i].index + matches[i][0].length, matches[i + 1]?.index || source.length).trim();
// Editorial directions are source context, not instructions or public article copy.
function clean(text) {
  return text.split(/\r?\n/).filter(line => !/^(_+|Important:|Website\/legal note:|Our website should eventually|Immediately below|\[)/.test(line)).join('\n').replace(/\n{3,}/g, '\n\n').trim();
}
const areas = {};
const areaMatches = [...sections[6].matchAll(/^(\d{2}) — ([^\r\n]+)\r?\n/gm)];
for (let i = 0; i < areaMatches.length; i++) areas[Number(areaMatches[i][1])] = {title: areaMatches[i][2], text: clean(sections[6].slice(areaMatches[i].index + areaMatches[i][0].length, areaMatches[i + 1]?.index || sections[6].length))};
const slug = text => text.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const entry = (title, summary, category, image, description, content, payload = {}) => ({title, slug: slug(title), short_description: summary, description, content, category, tags: [category, 'SIFI Foundation', 'Community-led development'], meta_title: title, meta_description: summary, featured_image: `/images/${image}`, payload});
const blogSpecs = [
  ['Why Local Voices Matter', 'How community knowledge, dignity and participation shape SIFI Foundation’s vision for inclusive development.', [1,2,3,4,5,7], 'Community Development', 'volunteer.jpg', 'A useful development programme begins with a conversation. Before choosing an activity, communities need space to describe the barriers they face, the resources they already have and the future they want to build. For SIFI Foundation, this listening process connects a broad vision of inclusion with practical local decisions.'],
  ['Health, Learning and Opportunity: An Integrated Development Framework', 'Explore how SIFI connects health, education, skills, livelihoods and sustainability across its areas of work.', [6,8,22], 'Development Priorities', 'education.jpg', 'Everyday development needs rarely arrive one at a time. Learning depends on wellbeing; livelihood opportunities depend on skills; and community resilience depends on the environment and essential services. SIFI Foundation brings these priorities into one connected framework while retaining the specialist attention each area needs.'],
  ['Partnerships That Begin with Community Priorities', 'A shared approach to CSR, institutional collaboration and responsible programme implementation.', [9,13,23], 'Partnerships', 'volunteer.jpg', 'A meaningful partnership starts by agreeing on the problem to solve. Community knowledge helps identify priorities, institutional resources make action possible, and professional implementation connects intentions to accountable delivery. SIFI Foundation’s partnership model brings these contributions together around locally relevant objectives.'],
  ['Measuring What Matters: Evidence, Learning and Accountability', 'Why baselines, community feedback and transparent reporting matter when assessing development outcomes.', [10,12,18], 'Research and Impact', 'Blog.png', 'An activity report can show what happened, but it cannot by itself explain what changed. SIFI Foundation’s approach to evidence connects initial needs, implementation quality and outcomes. It asks whether access improved, whether underserved groups participated and whether benefits can continue beyond a project period.'],
  ['Local Solutions, Lasting Change: Building Community Institutions', 'Learning centres, local capacity and inclusive institutions can strengthen community ownership of development.', [11,21], 'Community Institutions', 'about1.png', 'A community centre can be more than a building. It can become a place to learn, share information and discuss common priorities when the people who use it have a voice in its purpose. SIFI Foundation’s community-development model places participation and local capacity at the centre of these shared resources.'],
  ['Purpose, People and the Journey of SIFI Foundation', 'An introduction to the Foundation’s institutional journey, leadership and commitment to sustainable development.', [14,15,16], 'Foundation Updates', 'About.png', 'Institutional development gives a social purpose the structures it needs to grow responsibly. SIFI Foundation describes its journey as a move from field-oriented understanding towards a broader platform for programmes, research and partnerships. Its leadership message connects this growth with dignity, capability and meaningful community participation.'],
  ['Be Part of the Change: Ways to Work with SIFI Foundation', 'Discover ways to contribute expertise, volunteer, support programmes and start a conversation with SIFI.', [17,19,20], 'Get Involved', 'Getinvolbed.png', 'People contribute to development in different ways. Some bring technical knowledge, some build institutional partnerships, and others share time or field experience. A useful first step is to connect that contribution with an identified community need and a clear role in the Foundation’s work.']
];
const blogs = blogSpecs.map(([title, summary, ids, category, image, intro]) => entry(title, summary, category, image, intro, ids.map(id => {
  let text = clean(sections[id]);
  if (id === 12) text = text.split('Impact Stories')[0].trim() + '\n\nImpact stories are planned around livelihoods, healthcare, education, women’s leadership and sustainability. Verified field documentation is needed before presenting these themes as individual beneficiary achievements.';
  if (id === 16) text = text.split('Suggested Timeline')[0].trim();
  return text;
}).join('\n\n'), {overview: 'Adapted from the SIFI Foundation organisational profile.'}));
const specs = [
  ['Healthcare and Public Health', [1], 'healthcare.jpg', 'Improve access to preventive, promotive and basic healthcare through community awareness and locally relevant support.', 'Underserved communities, including mothers, children and people facing barriers to basic healthcare.', 'Improved access to health information and services; stronger awareness of nutrition, hygiene and preventive care.'],
  ['Education and Digital Learning', [2,17], 'education.jpg', 'Connect education support, literacy and digital inclusion so learners can participate with confidence.', 'Children, young people and disadvantaged learners facing educational or digital access barriers.', 'More accessible learning resources, greater digital confidence and stronger continuity of learning.'],
  ['Skill Development, Employment and Entrepreneurship', [3], 'volunteer.jpg', 'Build practical capabilities that connect young people and women with employment and enterprise opportunities.', 'Youth, women and people seeking vocational, technical or employment-oriented skills.', 'Stronger vocational capabilities, improved employability and better preparation for enterprise.'],
  ['Livelihood Promotion and Economic Empowerment', [4], 'about1.png', 'Support sustainable income opportunities through enterprise development, financial literacy and market-oriented initiatives.', 'Individuals and communities seeking self-employment and more secure sources of income.', 'Improved financial understanding, viable enterprise planning and stronger access to livelihood opportunities.'],
  ['Women and Girl Empowerment', [5], 'volunteer.jpg', 'Connect education, health, skills, financial inclusion and leadership opportunities for women and girls.', 'Women and girls, with attention to underserved and vulnerable communities.', 'Greater participation in education, enterprise and community decisions, supported by practical capabilities.'],
  ['Sustainable Agriculture and Allied Livelihoods', [6,7], 'food.jpg', 'Bring climate-responsive farming together with livestock, dairy, fisheries and related rural livelihood support.', 'Farmers and rural households dependent on agriculture, livestock, dairy, fisheries or aquaculture.', 'Stronger agricultural knowledge, responsible resource practices and improved readiness for market linkages and value addition.'],
  ['Environment, Climate Action and Clean Energy', [8,9], 'hero.jpg', 'Connect biodiversity, climate awareness and resource conservation with practical renewable-energy learning.', 'Communities seeking healthier ecosystems and accessible knowledge about sustainable energy.', 'Greater environmental awareness, stronger conservation participation and informed decisions about clean energy.'],
  ['Water, Sanitation, Hygiene and Waste Management', [10], 'healthcare.jpg', 'Promote safe water, conservation, hygiene and responsible waste practices as interconnected community priorities.', 'Communities facing gaps in water access, sanitation, hygiene information or waste management.', 'Better understanding of water safety and conservation, cleaner shared spaces and responsible waste practices.'],
  ['Inclusive Community Development and Humanitarian Resilience', [11,13,14,15,16,18], 'elderly.jpg', 'Strengthen local institutions and essential services while supporting inclusion, culture and emergency resilience.', 'Rural and tribal communities, children, senior citizens, persons with disabilities and people affected by emergencies.', 'More inclusive community participation, stronger local capacity and better preparedness for disruptions.'],
  ['Research, Baseline Studies and Social Impact Assessment', [12], 'Blog.png', 'Generate reliable evidence to identify priorities, establish baselines and improve programme decisions.', 'Communities and institutions participating in development planning, implementation and evaluation.', 'Clearer needs assessments, useful monitoring information and transparent documentation of outcomes and learning.']
];
const programmes = specs.map(([title, ids, image, objective, beneficiaries, outcomes]) => entry(title, objective, areas[ids[0]].title, image, objective + '\n\n' + 'This programme area reflects SIFI Foundation’s commitment to inclusive, participatory and evidence-based development. Specific activities are shaped by community needs, local resources and appropriate partnerships.', ids.map(id => areas[id].title + '\n\n' + areas[id].text).join('\n\n'), {
  overview: objective, objectives: objective, targetBeneficiaries: beneficiaries,
  keyActivities: ids.map(id => areas[id].text).join('\n\n'),
  outcomes: 'Intended outcomes: ' + outcomes,
  impactSummary: 'Assessment focuses on reach, access, outcomes, inclusion, sustainability and learning. Achieved results require verified programme records.',
  contactEmail: 'projects@sififoundation.org', contactPhone: '0651-3591618',
  websiteUrl: 'https://www.sififoundation.org',
  problemStatement: 'Community consultations and baseline assessment identify local barriers before programme activities are designed.'
}));
const storySpecs = [
  ['From Need to Opportunity', 'Skills and enterprise support can create a pathway towards more secure livelihoods.', 3, 'A livelihood challenge is often a combination of limited training, uncertain market access and low financial confidence. Listening to these connected barriers is the starting point for useful support.', 'Vocational learning, entrepreneurship development and financial literacy can be brought together around locally relevant opportunities.', 'The pathway moves from understanding existing capabilities to developing skills, exploring viable enterprise options and reviewing whether support improves access to income opportunities.'],
  ['A Healthier Community', 'Community outreach and preventive care can help bring essential health information and support closer to people.', 0, 'When health information and basic services are difficult to access, families can struggle to identify available support. Community priorities help shape the response.', 'Health outreach, preventive awareness, nutrition information and maternal and community-health support form part of the Foundation’s healthcare focus.', 'A responsible account follows the journey from an identified access barrier through outreach and support, then examines whether people could use the information or services offered.'],
  ['Learning Beyond the Classroom', 'Education support and digital learning can open more accessible routes to knowledge and confidence.', 1, 'Learning opportunities depend on access to materials, supportive spaces and the ability to use available technology. Disadvantaged learners may face several of these barriers together.', 'Libraries, learning centres, study materials, literacy initiatives and digital education offer complementary ways to support participation.', 'The learning pathway starts with the learner’s needs, connects them to relevant resources and reviews participation and learning progress without assuming that access alone guarantees achievement.'],
  ['Women Creating Change', 'Education, enterprise and leadership opportunities can strengthen women’s participation in community life.', 4, 'Women’s participation can be affected by interconnected gaps in education, healthcare, skills and financial inclusion. A community-based approach considers these needs together.', 'The Foundation’s empowerment focus connects skills and entrepreneurship with awareness, financial inclusion and leadership development.', 'The pathway centres women’s own priorities, builds practical capabilities and considers whether participation in livelihood and community opportunities becomes more accessible.'],
  ['Sustainable Communities', 'Local participation can connect environmental responsibility, water conservation and resilient livelihoods.', 6, 'Environmental pressures intersect with agriculture, water use, energy and everyday community wellbeing. Practical responses need to reflect local ecosystems and resources.', 'Environmental education, biodiversity conservation, climate awareness, sustainable farming and water conservation provide connected entry points for community action.', 'Communities can begin by identifying shared resource concerns, selecting appropriate practices and reviewing whether those practices are maintained and useful over time.']
];
for (const programme of programmes) {
  programme.content += '\n\nWho the programme is designed to support\n' + programme.payload.targetBeneficiaries
    + '\n\nFrom needs to implementation\n' + clean(sections[7])
    + '\n\nIntended outcomes and learning\n' + programme.payload.outcomes + '\n\n' + programme.payload.impactSummary;
}
const stories = storySpecs.map(([title, summary, index, background, intervention, journey]) => entry(title, 'Impact pathway: ' + summary, 'Impact Pathways', programmes[index].featured_image.replace('/images/', ''), 'This is a programme-based impact pathway drawn from the Foundation’s profile, not a verified individual beneficiary case study.', [background, intervention, journey, 'Evidence for a future field story would include a documented starting point, the support provided, participant consent and verified outcomes. The Foundation’s impact framework asks what changed, who could participate and whether benefits can continue.'].join('\n\n'), {background, challenge: background, intervention, supportProvided: 'Programme focus: ' + programmes[index].title, journey, impact: 'Intended change: ' + summary, result: 'Verified beneficiary results are not supplied in the organisational profile.', programmeSlug: programmes[index].slug}));
// Reuse the original demo story row rather than leaving an extra sixth story.
stories[3].slug = 'women-leading-local-change';
fs.writeFileSync(path.join(__dirname, 'foundation-content.json'), JSON.stringify({blogs, programmes, impact_stories: stories}, null, 2) + '\n');
